# Site settings
title: Nu Documentation
email: development@nubits.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for how to use and integrate with the Nu cryptoasset client,
  core protocol and its consensus and transactional tokens, NuShares (NSR) and
  NuBits (NBT).

url: "https://docs.nubits.com"   # with the https protocol
baseurl: ""
enforce_ssl: "docs.nubits.com"  # without any protocol
imageurl:
  kb: "/kb/images/"
  history: "/history/images/"
historyurl:
  kb: "https://github.com/NuNetwork/documentation/commits/gh-pages/_kb/"
  history: "https://github.com/NuNetwork/documentation/commits/gh-pages/_history/"
suggesturlbase:
  kb: "https://docs.nubits.com/"
  history: "https://timeline.nubits.com"

# Previous domain settings
# (Keeping until we're sure we don't need them any longer; useful for any ports of this repo for other documentation uses, for instance, Peershares)
#url: "http://nunetwork.github.io" # the base hostname & protocol for your site
#baseurl: "/documentation" # the subpath of your site, e.g. /blog/
#suggesturlbase: https://nunetwork.github.io/documentation

# Content collections
collections:
  kb:
    output: true
  history:
    output: true

# Build settings
#markdown: redcarpet
#redcarpet:
#  extensions: ['smart', 'superscript']
kramdown:
  input: GFM

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
